name=pocdb-postgres-connector
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
 
database.hostname=localhost
database.port=5432
database.user=debezium
database.password=dbz
database.dbname=pocdb
 
topic.prefix=pocdb
plugin.name=pgoutput
 
slot.name=debezium_poc_slot
publication.name=debezium_poc_pub
 
table.include.list=public.person, public.application, public.plan_enrollment
schema.include.list=public
 
snapshot.mode=initial
